"""Email digest of new A/B tier candidates."""

import logging
import smtplib
from datetime import datetime, timedelta
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from sqlalchemy import text

from openclaw.config import settings
from openclaw.db.session import SessionLocal

logger = logging.getLogger(__name__)

DIGEST_SQL = text("""
    SELECT
        c.score_tier, c.potential_splits, c.estimated_margin_pct,
        c.estimated_profit, c.estimated_arv, c.flagged_for_review,
        p.address, p.county, p.parcel_id AS parcel_code, p.assessed_value
    FROM candidates c
    JOIN parcels p ON c.parcel_id = p.id
    WHERE c.created_at >= :since
        AND c.score_tier IN ('A', 'B')
    ORDER BY c.score_tier, c.estimated_margin_pct DESC
""")


def build_html(rows: list[dict]) -> str:
    """Render candidate rows as an HTML email table."""
    header = """
    <html><body>
    <h2>Mike's BS — New Subdivision Candidates</h2>
    <table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;font-family:sans-serif;font-size:14px">
    <tr style="background:#333;color:#fff">
        <th>Tier</th><th>Address</th><th>County</th><th>Splits</th>
        <th>Margin %</th><th>Est. Profit</th><th>Assessed</th><th>Flagged</th>
    </tr>
    """
    body = ""
    for r in rows:
        color = "#e8f5e9" if r["score_tier"] == "A" else "#fff3e0"
        body += f"""
        <tr style="background:{color}">
            <td><b>{r['score_tier']}</b></td>
            <td>{r['address'] or 'N/A'}</td>
            <td>{r['county']}</td>
            <td>{r['potential_splits']}</td>
            <td>{r['estimated_margin_pct']:.1f}%</td>
            <td>${r['estimated_profit']:,}</td>
            <td>${r['assessed_value'] or 0:,}</td>
            <td>{'⚠️' if r['flagged_for_review'] else '✓'}</td>
        </tr>
        """
    footer = "</table><p style='color:#888;font-size:12px'>Generated by Mike's Building System</p></body></html>"
    return header + body + footer


def send_digest() -> int:
    """Query new A/B candidates from last 24h and email digest. Returns count sent."""
    session = SessionLocal()
    try:
        since = datetime.utcnow() - timedelta(hours=24)
        result = session.execute(DIGEST_SQL, {"since": since})
        rows = [dict(r) for r in result.mappings()]

        if not rows:
            logger.info("No new A/B candidates — skipping digest")
            return 0

        html = build_html(rows)
        count = len(rows)

        if not settings.SMTP_HOST or not settings.NOTIFY_EMAIL:
            logger.warning(f"SMTP not configured — would have sent digest with {count} candidates")
            return count

        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"Mike's BS: {count} New Subdivision Candidates"
        msg["From"] = settings.SMTP_USER
        msg["To"] = settings.NOTIFY_EMAIL
        msg.attach(MIMEText(html, "html"))

        with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as server:
            server.starttls()
            server.login(settings.SMTP_USER, settings.SMTP_PASS)
            server.send_message(msg)

        logger.info(f"Sent digest with {count} candidates to {settings.NOTIFY_EMAIL}")
        return count
    finally:
        session.close()


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    send_digest()
